### ISSUE TITLE
camelCase vs snake_case

### ISSUE THREAD

**Issue by slifty** [dynajoe/tinypg#31]
Hey all -- first, thank you for the tool, it allows for some pretty elegant database logic!

## The Problem
I am looking to use `tinypg` in a project and wanted to see if you had yet thought about this code style question in terms of recommended practice alongside your tool.

Node / JS tends to prefer `camelCase` for things like object attributes (and indeed I believe airbnb lint settings require it).

Meanwhile, postgres strongly prefers `snake_case` for column names.

## The Context
ORMs like Sequelize let you deal with this using the `underscored` flag when defining your model (search [this documentation](https://sequelize.org/v7/class/lib/model.js~Model.html) for "underscored").

My instinct is that it would be nice for tinypg to convert the object structure outside of SQL, allowing me define my queries as `select * from table` rather than having to explicitly list each field in order to specify "camel_case as camelCase"

That said, maybe you would suggest that it's best practice to explicitly list the columns anyway and adjust the queries as necessary if the schema changes in order to be more explicit in the shape of their return values.

## The Question

What do you all suggest as `tinypg`'s recommended pattern for addressing the discrepancy for camelCase in node vs snake_case in psql?

**Comment by slifty** [comment]
If I'm understanding hooks correctly, maybe I could implement this as a QueryResult hook?

(and if you thought this use case was common enough then maybe you would would consider providing the implemented hook as part of tinypg which the user could either use or not use as needed)

**Comment by stephenreddek** [comment]
As a user of tinypg, I would recommend that mapping in your js/ts rather than in your queries. I think explicitly mapping to your model in js/ts gives you extra protection against any other problems that could creep up. You can do some extra validation in that process as well (we use the "decoder" pattern).
