### ISSUE TITLE
Replacing pg-format package

### ISSUE THREAD

**Issue by manuganji** [dynajoe/tinypg#32]
Hi, I ran into `vite` compile errors when using your package. The errors originated in `pg-format` package. That repo appears to be [unmaintained](https://github.com/datalanche/node-pg-format/pull/30) and probably not depending on that package is a better idea. 

You're only using it one place.

https://github.com/dynajoe/tinypg/blob/cbc755d8abcb153e1a8dee4f0a67e074479657b6/src/tiny.ts#L523

Maybe let's change this call to the one [natively offered](https://www.postgresql.org/docs/current/functions-string.html#FUNCTIONS-STRING-FORMAT)? 

e.g. `SELECT format('INSERT INTO %I VALUES(%L)', 'locations', 'C:\Program Files');`

I think this change would drop support for named arguments but I think that's better than the current unusable state.

**Comment by stephenreddek** [comment]
A fork such as github.com/ScaleLeap/pg-format could maintain current functionality and receive these updates. It does fix this issue too.
