### ISSUE TITLE
Syntax error when creating a parameterized schema

### ISSUE THREAD

**Issue by slifty** [dynajoe/tinypg#36]
This may well be just me making a mistake, but I'm feeling stumped so wanted to open an issue in case there's something else going on.

I have a query to create a schema:

*test/createSchema.sql*
```
CREATE SCHEMA :schemaName;

```

I have a call to invoke that query:

```
db.sql(
  'test.createSchema',
  { schemaName: 'test' }
);
```

I am getting the following error:

```
    [test_createSchema]

    CREATE SCHEMA :schemaName;

    error: syntax error at or near "$1"
```

If I edit my .sql to just be literally (no parameter) `CREATE SCHEMA "test"` it works.
If I write `CREATE SCHEMA 'test'` I do get the syntax error.

Any clue what I'm doing wrong here?  Is it possible there's a bug?  Is parameterization for this type of query just not supported?

**Comment by jasonaowen** [comment]
This error does not come from TinyPg; it is being generated by pg-protocol on behalf of PostgreSQL. From the [node-postgres docs](https://node-postgres.com/features/queries#parameterized-query):

> PostgreSQL does not support parameters for identifiers. If you need to have dynamic database, schema, table, or column names (e.g. in DDL statements) use [pg-format](https://www.npmjs.com/package/pg-format) package for handling escaping these values to ensure you do not have SQL injection!

This is also somewhat evident in the [PostgreSQL docs for `PREPARE`](https://www.postgresql.org/docs/current/sql-prepare.html#id-1.9.3.158.7) (although in practice you are probably not using that; I couldn't find a better reference to cite):

> statement: Any `SELECT`, `INSERT`, `UPDATE`, `DELETE`, or `VALUES` statement.

So, not a bug, nor a limitation in any of the JavaScript code, but at the protocol level. No parameters for DDL!

**Comment by slifty** [comment]
@jasonaowen Ah HA great point -- so it goes!

Given that the solution I suppose will have to just be to not use `.sql` but to use `.query` for DDL and just construct the raw string directly and just make sure the parameter has been properly sanitized.
